#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# lint
for file in $(git diff --cached --name-only --diff-filter=ACMRTU | grep -v "package-lock.json\|package.json" | grep -E '\.(ts|js|json)$')
do
  git show ":$file" | npx eslint --stdin --stdin-filename "$file" # lint staged changes only
  if [ $? -ne 0 ]; then
    echo "Lint failed on staged file '$file'."
    exit 1
  fi
done